### ISSUE TITLE
Save-Module instead of Install-Module

### ISSUE THREAD

**Issue by FISHMANPET** [umn-microsoft-automation/AzureDevOpsTemplates#3]
Instead of using Install-Module and requring the agent to run as admin, use save-module and save it in the default path, then the agent only needs permissions to write to the PowerShell module folder but otherwise doesn't need admin

**Comment by travis-sobeck** [comment]
Will it save it in subfolder based on module version?

**Comment by FISHMANPET** [comment]
It does! It's kind of magical how well it works actually

**Comment by travis-sobeck** [comment]
sweet!

**Comment by FISHMANPET** [comment]
Whoops did this in #4
